--CREATE TABLE TB_USER (
--    ID VARCHAR2(20) NOT NULL,
--    PWD VARCHAR2(100) NOT NULL
--);
--
--ALTER TABLE TB_USER
--ADD CONSTRAINT PK_DP_API_MNG PRIMARY KEY (ID);
--
--COMMENT ON COLUMN TB_USER.ID IS 'ID';
--COMMENT ON COLUMN TB_USER.PWD IS 'PASSWORD';

INSERT INTO TB_USER (ID, PWD) VALUES ('abc', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc0', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc1', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc2', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc3', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc4', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc5', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc6', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc7', 'abc');
INSERT INTO TB_USER (ID, PWD) VALUES ('abc8', 'abc');
